BaseUrl: /
disablePathToLower: true
languageCode: en-us
title: Alex Bachuk
LanguageCode: "en-US"
paginate: 5
DisqusShortname: YOUR_SHORT_NAME_HERE
Copyright: All rights reserved - 2017
canonifyurls: true
permalinks:
  post: /:slug/
  page: /:slug/
menu:
  main:
      - Name: "about hugo"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "about"
        URL: "/about/"
      - Name: "contact"
        Pre: "<i class='fa fa-road'></i>"
        Weight: -100
        URL: "/contact/"
params:
  description: JavaScript developer
  metadescription: Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead
  cover: none
  author: Alex Bachuk
  authorlocation: Fairfield, CT
  authorwebsite: https://alexbachuk.com
  bio: my bio
  logo: images/ab-logo.svg
  googleAnalyticsUserID: UA-23815614-1
  RSSLink: http://feeds.feedburner.com/...
  githubName: abachuk
  twitterName: netxm
  linkedinName: alexbachuk
  hideHUGOSupport: true
  social:
    twitter: netxm
